spring:
  application:
    name: BillingSystem

  datasource:
    url: jdbc:postgresql://localhost:5432/dbname
    username: 
    password: 

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8096
